import fs from "node:fs/promises";
import path from "node:path";
import type { ScanReport, SeverityCounts } from "@overlay/shared";

const REPORTS_DIR = path.join(process.cwd(), "data", "security-scans");
const RETENTION_COUNT = 30;

// Report ids are generated by us (see makeReportId) and also come back from
// clients as a route param — validate strictly since they become part of a
// filename read straight off disk.
const ID_PATTERN = /^\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}$/;

export function isValidReportId(id: string): boolean {
  return ID_PATTERN.test(id);
}

export function makeReportId(date: Date = new Date()): string {
  return date.toISOString().replace(/[:.]/g, "-").slice(0, 19);
}

function reportPath(id: string): string {
  return path.join(REPORTS_DIR, `${id}.json`);
}

export async function saveReport(report: ScanReport): Promise<void> {
  if (!isValidReportId(report.id)) {
    throw new Error(`Refusing to save report with malformed id: ${report.id}`);
  }
  await fs.mkdir(REPORTS_DIR, { recursive: true });
  const tmpFile = `${reportPath(report.id)}.tmp`;
  await fs.writeFile(tmpFile, JSON.stringify(report, null, 2), "utf8");
  await fs.rename(tmpFile, reportPath(report.id));
  await pruneOldReports();
}

export async function getReport(id: string): Promise<ScanReport | undefined> {
  if (!isValidReportId(id)) return undefined;
  try {
    const raw = await fs.readFile(reportPath(id), "utf8");
    return JSON.parse(raw) as ScanReport;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw err;
  }
}

export interface ScanReportSummary {
  id: string;
  startedAt: string;
  finishedAt: string;
  durationSeconds: number;
  summary: SeverityCounts;
}

async function listReportIds(): Promise<string[]> {
  let entries: string[];
  try {
    entries = await fs.readdir(REPORTS_DIR);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw err;
  }
  return entries
    .filter((name) => name.endsWith(".json") && !name.endsWith(".tmp"))
    .map((name) => name.slice(0, -".json".length))
    .filter(isValidReportId)
    .sort()
    .reverse(); // newest first, ids are lexicographically sortable ISO-ish timestamps
}

export async function listReports(): Promise<ScanReportSummary[]> {
  const ids = await listReportIds();
  const summaries = await Promise.all(
    ids.map(async (id) => {
      const report = await getReport(id);
      if (!report) return null;
      return {
        id: report.id,
        startedAt: report.startedAt,
        finishedAt: report.finishedAt,
        durationSeconds: report.durationSeconds,
        summary: report.summary,
      } satisfies ScanReportSummary;
    }),
  );
  return summaries.filter((s): s is ScanReportSummary => s !== null);
}

export async function getLatestReport(): Promise<ScanReport | undefined> {
  const ids = await listReportIds();
  if (ids.length === 0) return undefined;
  return getReport(ids[0]);
}

async function pruneOldReports(): Promise<void> {
  const ids = await listReportIds();
  const toDelete = ids.slice(RETENTION_COUNT);
  await Promise.all(toDelete.map((id) => fs.rm(reportPath(id), { force: true })));
}
